### ISSUE TITLE
Starting Container

### ISSUE THREAD

**Issue by jpcapone** [Soren90/cs2-docker#10]
When I start the container I get the error listed below:

/mnt/server/cs2/game/cs2.sh: No such file or directory

here is my compose file

```
`version: "3.7"

services:
  cs2:
    image: soren90/cs2:latest
    container_name: cs2-ds

    environment:
      SERVER_HOSTNAME: "XXXXX"
      RCON_PASSWORD: "XXXXXX" 
      IP: 0.0.0.0 
      PORT: 27015
      GAME_TYPE: 0
      GAME_MODE: 1
      MAP: de_inferno
      MAXPLAYERS: 12
      MAPGROUP: mg_active
      GSLT: XXXXXXXXXXXXXXXXXXXXX
      EXTRAARG: #Extra Launch options

    volumes:
      - /var/lib/docker/volumes/cstrike2:/mnt/server
      
    network_mode: "host"

    restart: unless-stopped
    stdin_open: true
    tty: true
  rconpanel:
    image: soren90/rcon-panel
    ports:
      - "3000:3000"
    restart: unless-stopped`
```
I would appreciate any suggestions.

**Comment by Soren90** [comment]
Most likely the update of the game didn't go through. Could you share your log from this?

**Comment by Soren90** [comment]
Also. This seems a little strange to me:

    volumes:
      - /var/lib/docker/volumes/cstrike2:/mnt/server

That's not where you are supposed to put things. (Especially considering that all volume data is put into a _data folder and not directly in the folder you use)

I don't know what the consequences are to use bind mount on the volume path, but that is not how you are supposed to do it. Either you use volume mount as I've documented, or you use bind mount in a separate folder (haven't tested this scenario, but I don't see why it shouldn't work)

**Comment by Soren90** [comment]
Did you figure it out?

**Comment by jpcapone** [comment]
> Did you figure it out?

Naaa.  I switched over to joedwards32/cs2.....

**Comment by Soren90** [comment]
> > Did you figure it out?
> 
> Naaa. I switched over to joedwards32/cs2.....

All right. I'm running this container locally myself and it should work fine. 

Are you planning on doing more troubleshooting or can I consider this solved?

**Comment by jpcapone** [comment]
> > > Did you figure it out?
> > 
> > 
> > Naaa. I switched over to joedwards32/cs2.....
> 
> All right. I'm running this container locally myself and it should work fine.
> 
> Are you planning on doing more troubleshooting or can I consider this solved?

I would be willing to try it again to help you out but every single one of my containers uses the same format for bind mounts. i.e.
```

volumes:
  - /var/lib/docker/volumes/cstrike2:/mnt/server
```
  - 
So I don't understand why your container should be any different using 

```
    volumes:
      - type: volume
        source: cs2-data
        target: /mnt/server
```
Ill try it the way you suggest right now.
